theme: jekyll-theme-cayman
title: EasyPipe
description: Data Streaming is Easy
logo: /img/easy-pipe.png

github:
  owner_name: Dmytro Patserkovskyi

links:
  travis: https://travis-ci.org/dmytro-winged/easy-pipe
  sonar: https://sonarcloud.io/dashboard?id=com.altumpoint.easypipe%3Aeasypipe-parent
  bintray: https://bintray.com/dmytro-winged/maven/easy-pipe